import {agent,owner,database,bucket,response,privateState,txt,safeUrl,date,mutate} from '@/lib/workspace';
export async function GET(req:Request){if(!agent(req))return response({error:'Unauthorized'},401);return response(await privateState());}
export async function POST(req:Request){if(!agent(req)&&!await owner())return response({error:'Unauthorized'},401);const origin=req.headers.get('Origin');if(origin&&origin!==new URL(req.url).origin)return response({error:'Forbidden'},403);try{const p=await req.json() as Record<string,any>;const db=database(),at=date();
 if(p.kind==='action'){if(!agent(req))return response({error:'Agent token required'},403);return response(await mutate(p));}
 if(p.kind==='automation'){if(!agent(req))return response({error:'Agent token required'},403);await db.prepare('INSERT OR REPLACE INTO settings(key,value) VALUES(?,?)').bind('automation',JSON.stringify({enabled:!!p.enabled,hour:9,mail:'gmail-codex',github:'https://github.com/girenok77/ai-engineer-portfolio'})).run();return response({ok:true});}
 if(p.kind==='prepare'){if(!agent(req))return response({error:'Agent token required'},403);const a=await db.prepare('SELECT * FROM applications WHERE id=?').bind(txt(p.id)).first<any>();if(!a||!['draft','review'].includes(a.status)||a.send_lock)throw Error('Заявка вже схвалена або надіслана');if(!await db.prepare('SELECT id FROM cvs WHERE id=?').bind(txt(p.cvId)).first())throw Error('CV не знайдено');if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(p.emailTo||''))throw Error('Email потрібен');await db.prepare('UPDATE applications SET status=?,cv_id=?,prepared_cv_id=?,email_to=?,email_subject=?,email_body=?,gmail_draft_id=?,updated_at=? WHERE id=?').bind('review',p.cvId,p.cvId,txt(p.emailTo,300),txt(p.subject,500),txt(p.body),txt(p.draftId,300),at,a.id).run();return response({ok:true});}
 if(p.kind==='claim'){if(!agent(req))return response({error:'Agent token required'},403);const lock=crypto.randomUUID();const a=await db.prepare("UPDATE applications SET status='sending',send_lock=?,updated_at=? WHERE id=? AND status='approved' AND send_lock IS NULL AND gmail_draft_id IS NOT NULL AND prepared_cv_id=cv_id RETURNING *").bind(lock,at,txt(p.id)).first();if(!a)return response({error:'Заявка не схвалена або вже взята на надсилання'},409);return response({ok:true,application:a});}
 if(p.kind==='complete'){if(!agent(req))return response({error:'Agent token required'},403);if(!p.messageId)throw Error('Потрібен підтверджений Gmail message ID');const a=await db.prepare("UPDATE applications SET status='sent',sent_at=?,gmail_message_id=?,gmail_thread_id=?,send_lock=NULL,updated_at=? WHERE id=? AND status='sending' AND send_lock=? RETURNING id").bind(at,txt(p.messageId,300),txt(p.threadId,300),at,txt(p.id),txt(p.lock)).first();if(!a)throw Error('Невірний блокувальний ключ');return response({ok:true});}
 if(p.kind==='jobs'){const statements=[];for(const j of (p.jobs||[]).slice(0,300)){const active=j.active===false?0:1;statements.push(db.prepare('INSERT INTO jobs(id,title,company,location,url,description,published,expires,active,score,category,reasons,first_seen) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET title=excluded.title,company=excluded.company,location=excluded.location,url=excluded.url,description=excluded.description,published=excluded.published,expires=excluded.expires,active=excluded.active,score=excluded.score,category=excluded.category,reasons=excluded.reasons').bind(txt(j.id,200),active?txt(j.title,500):'Неактивна вакансія',active?txt(j.company,500):'',txt(j.location,500),safeUrl(j.url),active?txt(j.description):'',txt(j.published,100),txt(j.expires,100),active,Math.max(0,Math.min(100,Number(j.score)||0)),txt(j.category,40),JSON.stringify(j.reasons||[]),at));}if(p.cursor)statements.push(db.prepare('INSERT OR REPLACE INTO settings(key,value) VALUES(?,?)').bind('nav_cursor',JSON.stringify(p.cursor)));if(statements.length)await db.batch(statements);return response({ok:true,count:statements.length});}
 if(p.kind==='sessions'){const statements=(p.sessions||[]).slice(0,2000).map((s:any)=>db.prepare('INSERT OR REPLACE INTO sessions(id,day,project,started_at,ended_at,active_seconds,elapsed_seconds,input_tokens,cached_tokens,output_tokens,total_tokens,source) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').bind(txt(s.id,150),txt(s.day,10),txt(s.project,200),txt(s.startedAt,50),txt(s.endedAt,50),Math.max(0,Number(s.activeSeconds)||0),Math.max(0,Number(s.elapsedSeconds)||0),s.inputTokens??null,s.cachedTokens??null,s.outputTokens??null,s.totalTokens??null,'codex-local'));if(statements.length)await db.batch(statements);return response({ok:true,count:statements.length});}
 if(p.kind==='cv'){if(!['base','adapted'].includes(p.cvKind))throw Error('Тип CV');const bytes=Uint8Array.from(atob(p.base64),c=>c.charCodeAt(0));if(bytes.length>5_000_000)throw Error('Максимум 5 МБ');const filename=txt(p.filename,200);if(!/\.(docx|pdf|txt)$/i.test(filename))throw Error('Формат: DOCX, PDF або TXT');const id=crypto.randomUUID(),key='cv/'+id,textKey=p.text?'cv-text/'+id:null;await bucket().put(key,bytes,{httpMetadata:{contentType:filename.endsWith('.pdf')?'application/pdf':filename.endsWith('.docx')?'application/vnd.openxmlformats-officedocument.wordprocessingml.document':'text/plain'}});if(textKey)await bucket().put(textKey,txt(p.text,100000));await db.prepare('INSERT INTO cvs(id,application_id,filename,object_key,text_key,created_at,kind) VALUES(?,?,?,?,?,?,?)').bind(id,p.applicationId||null,filename,key,textKey,at,p.cvKind).run();return response({ok:true,id});}
 if(p.kind==='run'){await db.prepare('INSERT INTO runs(id,kind,at,status,message) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),txt(p.runKind,40),at,txt(p.status,40),txt(p.message,3000)).run();return response({ok:true});}
 if(p.kind==='reply'){const a=await db.prepare('SELECT id FROM applications WHERE id=?').bind(p.applicationId).first();if(!a)throw Error('Невідома заявка');if(await db.prepare('SELECT id FROM replies WHERE id=?').bind(txt(p.id,200)).first())return response({ok:true,duplicate:true});await db.batch([db.prepare('INSERT OR IGNORE INTO replies(id,application_id,subject,body,received_at) VALUES(?,?,?,?,?)').bind(txt(p.id,200),p.applicationId,txt(p.subject,500),txt(p.body),txt(p.receivedAt,50)),db.prepare('UPDATE applications SET status=?,reply_at=?,updated_at=? WHERE id=?').bind('reply',p.receivedAt,at,p.applicationId)]);return response({ok:true});}
 throw Error('Невідомий тип');
 }catch(e){return response({error:e instanceof Error?e.message:'Помилка імпорту'},400);}}
