'use client';
import {useEffect,useState} from 'react';
import {BriefcaseBusiness,Search,Send,Code2,Settings2,Globe,LockKeyhole,RefreshCw,FileText,Clock3,Mail,Check,ChevronDown,X,ExternalLink,SlidersHorizontal,GitBranch,CalendarDays,LoaderCircle,Plus,Download,ArrowUpRight} from 'lucide-react';
type Mode='public'|'private'|'sessions';
const cats:Record<string,string>={backend:'Python backend',fullstack:'Full-stack',automation:'Інтеграції та автоматизація',ai:'AI / LLM',data:'Data engineering',qa:'Test automation'};
const fmt=(n:number)=>new Intl.NumberFormat('uk-UA').format(n||0);
const day=(v:string)=>v?new Date(v).toLocaleDateString('uk-UA',{day:'numeric',month:'short',timeZone:'Europe/Oslo'}):'—';
const duration=(n:number)=>`${Math.floor(n/3600)} год ${Math.floor(n%3600/60)} хв`;
const oslo=(d=new Date())=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Oslo',year:'numeric',month:'2-digit',day:'2-digit'}).format(d);
const url=(v:string)=>/^https?:\/\//.test(v||'')?v:'#';
export default function Workspace({mode}:{mode:Mode}){
 const[data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('jobs'),[query,setQuery]=useState(''),[filter,setFilter]=useState(''),[settings,setSettings]=useState(false),[prefs,setPrefs]=useState<any>(null),[selected,setSelected]=useState<any>(null),[notice,setNotice]=useState(''),[status,setStatus]=useState(''),[cv,setCv]=useState(''),[notes,setNotes]=useState(''),[sent,setSent]=useState('');
 const privateMode=mode!=='public';
 async function load(){try{setError('');const r=await fetch(privateMode?'/api/workspace':'/api/public');const j:any=await r.json();if(!r.ok)throw Error(j.error);setData(j);setPrefs(j.preferences);}catch(e){setError(e instanceof Error?e.message:'Не вдалося завантажити дані');}}
 useEffect(()=>{load();},[mode]);
 async function action(p:any){setBusy(true);try{const r=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});const j:any=await r.json();if(!r.ok)throw Error(j.error);setNotice(j.message||'Збережено');if(j.ok!==false){setSelected(null);await load();}}catch(e){setNotice(e instanceof Error?e.message:'Помилка');}finally{setBusy(false);}}
 function edit(a:any){setSelected(a);setStatus(a.status);setCv(a.cv_id||'');setNotes(a.notes||'');setSent(a.sent_at?.slice(0,10)||'');}
 async function upload(file:File,applicationId?:string){setBusy(true);try{const bytes=new Uint8Array(await file.arrayBuffer());if(bytes.length>5e6)throw Error('Максимум 5 МБ');let binary='';bytes.forEach(b=>binary+=String.fromCharCode(b));const r=await fetch('/api/agent',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'cv',cvKind:applicationId?'adapted':'base',applicationId,filename:file.name,base64:btoa(binary)})});const j:any=await r.json();if(!r.ok)throw Error(j.error);setCv(j.id);setNotice('Версію CV збережено приватно');await load();}catch(e){setNotice(e instanceof Error?e.message:'Не вдалося завантажити CV');}finally{setBusy(false);}}
 const apps=data?.applications||[],sessions=data?.sessions||[],jobs=data?.jobs||[],today=oslo();
 const sentApps=apps.filter((a:any)=>a.sent_at),replyApps=sentApps.filter((a:any)=>a.reply_at),todaySessions=sessions.filter((s:any)=>s.day===today);
 const current=mode==='sessions'?'sessions':mode==='public'?'applications':tab;
 const visibleJobs=jobs.filter((j:any)=>(!filter||j.category===filter)&&[j.title,j.company,j.location,j.description].join(' ').toLowerCase().includes(query.toLowerCase()));
 const visibleApps=apps.filter((a:any)=>(!filter||a.status===filter)&&[a.title,a.company].join(' ').toLowerCase().includes(query.toLowerCase()));
 const runs=data?.runs||[];
 const days=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-(6-i));const key=oslo(d);const rows=sessions.filter((s:any)=>s.day===key);return {day:key,count:rows.length,seconds:rows.reduce((a:number,s:any)=>a+s.active_seconds,0),tokens:rows.reduce((a:number,s:any)=>a+(s.total_tokens||0),0)};});
 const maxSeconds=Math.max(3600,...days.map(d=>d.seconds));
 return <div className="shell"><aside className="sidebar"><a className="brand" href="/"><span className="brand-mark"><GitBranch size={23}/></span><span>career<span className="brand-sub">workspace</span></span></a><div className="sidebar-label">YE​​VHENII HYRENKO</div><nav><a className="nav" href="/"><FileText size={19}/>Моє резюме</a><a href="/workspace" className={current==='jobs'?'nav active':'nav'}><Search size={19}/>Підбір вакансій{privateMode&&<span className="nav-count">{jobs.length}</span>}</a>{privateMode&&<button className={current==='queue'?'nav active':'nav'} onClick={()=>{setTab('queue');setFilter('');setQuery('')}}><Send size={18}/>Мої заявки<span className="nav-count">{apps.length}</span></button>}<a className={mode==='public'?'nav active':'nav'} href="/applications"><Globe size={19}/>Публічний журнал</a><a className={current==='sessions'?'nav active':'nav'} href="/sessions"><Code2 size={19}/>Сесії Codex</a></nav><div className="sidebar-rule"/><div className="sidebar-label">ПІДКЛЮЧЕННЯ</div><div className="connection"><BriefcaseBusiness size={16}/><span>Arbeidsplassen NAV</span><span className="mini-label">API</span></div><div className="connection"><Mail size={16}/><span>Gmail · через Codex</span><span className="mini-label">API</span></div><div className="connection"><GitBranch size={16}/><a href="https://github.com/girenok77/ai-engineer-portfolio" target="_blank" rel="noopener noreferrer">GitHub</a><span className="mini-label">Repo</span></div><div className="sidebar-bottom"><div className="avatar">YH</div><div><b>Yevhenii Hyrenko</b><small>Python · AI development</small></div>{privateMode&&<button className="icon-btn" aria-label="Налаштування" onClick={()=>setSettings(true)}><Settings2 size={18}/></button>}</div></aside>
 <main className="main"><header className="topbar"><div className="breadcrumb">Робочий простір <span>/</span><b>{current==='jobs'?'Вакансії':current==='sessions'?'Сесії Codex':current==='queue'?'Мої заявки':'Публічний журнал'}</b></div><span className="access-label">{privateMode?<LockKeyhole size={14}/>:<Globe size={14}/>} {privateMode?'Особистий кабінет':'Публічна сторінка'}</span></header>
 {notice&&<div className="toast" role="status"><span>{notice}</span><button aria-label="Закрити" onClick={()=>setNotice('')}><X size={17}/></button></div>}
 <div className="page-head"><div><div className="eyebrow">{current==='sessions'?'ЩОДЕННА ПРАКТИКА':current==='jobs'?'ПОШУК РОБОТИ В НОРВЕГІЇ':'ВІДГУКИ НА ВАКАНСІЇ'}</div><h1>{current==='sessions'?'Ритм твоєї розробки':current==='jobs'?'Вакансії для наступного кроку':current==='queue'?'Мої заявки':'Пошук роботи. Відкритий прогрес.'}</h1><p>{current==='sessions'?'Сесії, час виконання й токени з локальних журналів Codex.':current==='jobs'?'Python, інтеграції та AI. Збережи вакансію й підготуй відгук.':current==='queue'?'Версія резюме, фактичне надсилання та відповіді роботодавця.':'Журнал надісланих заявок Yevhenii Hyrenko для перегляду прогресу.'}</p></div><div className="head-actions">{privateMode?<><button className="button" onClick={load}><RefreshCw size={16}/>Оновити</button><button className="button primary" onClick={()=>setSettings(true)}><SlidersHorizontal size={16}/>Налаштувати</button></>:<a className="button" href="/workspace"><LockKeyhole size={16}/>Мій кабінет</a>}</div></div>
 {error?<div className="error" role="alert">{error}<button className="button" onClick={load}>Спробувати ще раз</button></div>:!data?<div className="loading"><LoaderCircle className="spin"/>Завантажуємо дані…</div>:<>
 <div className="metric-grid">{(current==='sessions'?[
 ['Сесій сьогодні',todaySessions.length,<Code2 key="1" size={19}/>,'Виявлено за подіями Codex'],['Час виконання',duration(todaySessions.reduce((a:number,s:any)=>a+s.active_seconds,0)),<Clock3 key="2" size={19}/>,'Оцінка тривалості активних turns'],['Токенів сьогодні',fmt(todaySessions.reduce((a:number,s:any)=>a+(s.total_tokens||0),0)),<GitBranch key="3" size={19}/>,'Input + output; cache у складі input'],['Днів практики',new Set(sessions.map((s:any)=>s.day)).size,<CalendarDays key="4" size={19}/>,'За імпортованою історією']]:[
 [privateMode?'Підібрано вакансій':'Надіслано заявок',privateMode?jobs.length:sentApps.length,<BriefcaseBusiness key="1" size={19}/>,privateMode?'Збережені результати підбору':'Фактично зафіксовано'],['Надіслано цього тижня',sentApps.filter((a:any)=>Date.now()-new Date(a.sent_at).getTime()<7*864e5).length,<Send key="2" size={19}/>,'За останні 7 днів'],['Відповідей',replyApps.length,<Mail key="3" size={19}/>,'Заявки з отриманою відповіддю'],['Співбесіди',apps.filter((a:any)=>a.status==='interview').length,<CalendarDays key="4" size={19}/>,'Поточний статус']]).map(([label,value,icon,sub]:any)=><article className="metric" key={label}><div className="metric-top"><span>{label}</span>{icon}</div><strong>{value}</strong><small>{sub}</small></article>)}</div>
 {current==='jobs'&&<><div className="automation-banner"><div className="automation-icon"><RefreshCw size={24}/></div><div><b>Щоденний підбір · {prefs?.hour||9}:00, Осло</b><p>Перегляд нових оголошень → оцінка відповідності → черга заявок.</p></div><span className={data.automation?.enabled?"badge green":"badge amber"}>{data.automation?.enabled?"Codex · 09:00":"Розклад ще не ввімкнено"}</span></div><div className="section-heading"><h2>Нові можливості <span>{visibleJobs.length}</span></h2><span className="small-text">Джерело: Arbeidsplassen / NAV</span></div><div className="toolbar"><label className="searchbox"><Search size={18}/><input placeholder="Посада, компанія або навичка" value={query} onChange={e=>setQuery(e.target.value)}/></label><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Усі напрямки</option>{Object.entries(cats).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div>{visibleJobs.length?visibleJobs.map((j:any)=><article className="job" key={j.id}><div className="company-icon">{j.company.slice(0,1)||'N'}</div><div className="job-main"><div className="job-tags"><span>{cats[j.category]||'Software development'}</span><span>{j.location}</span><span>{day(j.published)}</span></div><h3>{j.title}</h3><p className="company-name">{j.company}</p><p className="job-description">{j.description.slice(0,220)}{j.description.length>220?'…':''}</p><div className="skill-tags">{JSON.parse(j.reasons||'[]').map((r:string)=><span key={r}>{r}</span>)}</div></div><div className="job-side"><span className="score">{j.score}<small>/100 збіг</small></span><a className="button compact" target="_blank" rel="noopener noreferrer" href={url(j.url)}>Оголошення<ExternalLink size={14}/></a><button disabled={busy||apps.some((a:any)=>a.job_id===j.id)} className="button primary compact" onClick={()=>action({action:'save',jobId:j.id})}>{apps.some((a:any)=>a.job_id===j.id)?<><Check size={15}/>У заявках</>:<><Plus size={15}/>До заявок</>}</button></div></article>):<Empty title="Вакансій за цими умовами ще немає" text="Після першої перевірки тут з’являться відповідні оголошення. Фільтри доступні в налаштуваннях."/>}<p className="small-text note">Оцінка показує текстові збіги. Обов’язкові вимоги й мову роботи потрібно перевіряти в оголошенні.</p></>}
 {(current==='applications'||current==='queue')&&<><div className="section-heading"><h2>{current==='queue'?'Черга та надіслані відгуки':'Журнал заявок'} <span>{visibleApps.length}</span></h2><span className="small-text">{privateMode?'Документи й листи доступні лише тобі':'CV та тексти листів приховані'}</span></div><div className="toolbar"><label className="searchbox"><Search size={18}/><input placeholder="Знайти вакансію або компанію" value={query} onChange={e=>setQuery(e.target.value)}/></label><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Усі статуси</option>{Object.entries(data.statuses).filter(([k])=>privateMode||!['draft','review','approved'].includes(k)).map(([k,v]:any)=><option key={k} value={k}>{v}</option>)}</select>{!privateMode&&<button className="button" onClick={()=>{const rows=['Дата,Посада,Компанія,Статус',...apps.map((a:any)=>[a.sent_at,a.title,a.company,data.statuses[a.status]].map(v=>'"'+String(/^[=+@-]/.test(String(v||''))?"'"+v:v||'').replaceAll('"','""')+'"').join(','))];const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+rows.join('\n')],{type:'text/csv;charset=utf-8'}));a.download='applications.csv';a.click();URL.revokeObjectURL(a.href);}}><Download size={16}/>Звіт CSV</button>}</div>{visibleApps.length?<div className="table-wrap"><table><thead><tr><th>Вакансія / компанія</th><th>Дата відгуку</th><th>Статус</th>{privateMode&&<th>Резюме / деталі</th>}</tr></thead><tbody>{visibleApps.map((a:any)=><tr key={a.id}><td><a href={url(a.url)} target="_blank" rel="noopener noreferrer"><b>{a.title}</b></a><small>{a.company}</small></td><td>{day(a.sent_at)}</td><td><span className={'badge '+(['interview','offer'].includes(a.status)?'green':a.status==='rejected'?'red':'blue')}>{data.statuses[a.status]}</span></td>{privateMode&&<td><button className="button compact" onClick={()=>edit(a)}><FileText size={15}/>Переглянути</button></td>}</tr>)}</tbody></table></div>:<Empty title={privateMode?'Почни зі збереженої вакансії':'Надісланих заявок поки немає'} text={privateMode?'Відкрий «Підбір вакансій» і додай цікаву позицію до черги.':'Після фактичного надсилання тут з’являться дата, вакансія та статус.'}/>}</>}
 {current==='sessions'&&<><div className="session-grid"><section className="panel"><div className="section-heading"><h2>Останні 7 днів</h2><span className="badge blue">Europe/Oslo</span></div><div className="chart">{days.map(d=><div className="chart-col" key={d.day}><small>{d.count} сес.</small><div className="chart-track"><div className="chart-bar" style={{height:Math.max(2,d.seconds/maxSeconds*100)+'%'}} title={duration(d.seconds)}/></div><span>{day(d.day+'T12:00:00Z')}</span></div>)}</div></section><section className="panel session-summary"><h2>Токени за 7 днів</h2><strong>{fmt(days.reduce((a,d)=>a+d.tokens,0))}</strong><div className="summary-row"><span>Вхідні</span><b>{fmt(sessions.filter((s:any)=>days.some(d=>d.day===s.day)).reduce((a:number,s:any)=>a+(s.input_tokens||0),0))}</b></div><div className="summary-row"><span>З них кешовані</span><b>{fmt(sessions.filter((s:any)=>days.some(d=>d.day===s.day)).reduce((a:number,s:any)=>a+(s.cached_tokens||0),0))}</b></div><div className="summary-row"><span>Вихідні</span><b>{fmt(sessions.filter((s:any)=>days.some(d=>d.day===s.day)).reduce((a:number,s:any)=>a+(s.output_tokens||0),0))}</b></div><p>Кешовані токени вже входять до вхідних. Це не оцінка вартості підписки.</p></section></div><div className="section-heading"><h2>Історія сесій</h2><span className="small-text">Без текстів промптів і розмов</span></div>{sessions.length?<div className="table-wrap"><table><thead><tr><th>Дата / проєкт</th><th>Час виконання</th><th>Токени</th><th>Джерело</th></tr></thead><tbody>{sessions.slice(0,100).map((s:any)=><tr key={s.id}><td><b>{day(s.started_at)}</b><small>{s.project}</small></td><td>{duration(s.active_seconds)}</td><td>{s.total_tokens===null?'Немає даних':fmt(s.total_tokens)}</td><td><span className="badge neutral">Codex · локальний журнал</span></td></tr>)}</tbody></table></div>:<Empty title="Статистика ще не імпортована" text="Локальний збирач передає лише час і лічильники токенів. Тексти розмов залишаються на комп’ютері."/>}<p className="small-text note">Сесія — група turns одного чату з перервами до 30 хв. Час — сума тривалості виконання turns; він не вимірює твою увагу чи час ручного кодування. Імпортуються також розмови: це активність Codex, а не автоматичне підтвердження написання коду.</p></>}
 {privateMode&&<div className="runs"><div className="section-heading"><h2>Останні перевірки</h2></div>{runs.length?runs.slice(0,4).map((r:any)=><div className="run" key={r.id}><Clock3 size={15}/><span>{day(r.at)} · {r.message}</span><span className="badge neutral">{r.status}</span></div>):<p className="small-text">Перевірок ще не було.</p>}</div>}
 </>}
 <footer>Yevhenii Hyrenko <span>·</span> Career Workspace <span>·</span> {privateMode?'Приватні дані захищені входом':'Публічний журнал пошуку роботи'}</footer></main>
 {settings&&prefs&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="Налаштування підбору"><div className="modal-title"><h2>Налаштування підбору</h2><button className="icon-btn" aria-label="Закрити" onClick={()=>setSettings(false)}><X/></button></div><p className="small-text">Норвегія · переїзд можливий · робоча англійська</p><label>Напрямки</label><div className="category-choices">{Object.entries(cats).map(([k,v])=><button className={prefs.categories.includes(k)?'choice selected':'choice'} key={k} onClick={()=>setPrefs({...prefs,categories:prefs.categories.includes(k)?prefs.categories.filter((x:string)=>x!==k):[...prefs.categories,k]})}>{prefs.categories.includes(k)&&<Check size={14}/>} {v}</button>)}</div><label>Ключові навички<input value={prefs.keywords} onChange={e=>setPrefs({...prefs,keywords:e.target.value})}/></label><label>Міста / регіони (порожньо — вся Норвегія)<input value={prefs.locations} onChange={e=>setPrefs({...prefs,locations:e.target.value})}/></label><div className="form-row"><label>Мова<select value={prefs.language} onChange={e=>setPrefs({...prefs,language:e.target.value})}><option value="english">Без явної вимоги норвезької</option><option value="all">Усі</option></select></label><label>Час перевірки, Осло<input type="number" min="0" max="23" value={prefs.hour} onChange={e=>setPrefs({...prefs,hour:Number(e.target.value)})}/></label></div><label className="check-label"><input type="checkbox" checked={prefs.excludeSenior} onChange={e=>setPrefs({...prefs,excludeSenior:e.target.checked})}/>Приховувати Senior / Lead / Principal</label><p className="small-text">Зміна часу тут зберігає побажання. Розклад Codex потрібно узгодити окремо. Gmail обробляється автоматизацією Codex. Надсилання — після перегляду чернетки й схвалення.</p><label>Базове резюме<input type="file" accept=".docx,.pdf,.txt" onChange={e=>{if(e.target.files?.[0])upload(e.target.files[0]);}}/></label><button disabled={busy} className="button primary full" onClick={async()=>{await action({action:'settings',value:prefs});setSettings(false);}}>Зберегти налаштування</button></section></div>}
 {selected&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="Деталі заявки"><div className="modal-title"><h2>{selected.title}</h2><button className="icon-btn" aria-label="Закрити" onClick={()=>setSelected(null)}><X/></button></div><p>{selected.company}</p><label>Статус<select value={status} onChange={e=>setStatus(e.target.value)}>{Object.entries(data.statuses).map(([k,v]:any)=><option key={k} value={k}>{v}</option>)}</select></label><label>Версія резюме<select value={cv} onChange={e=>setCv(e.target.value)}><option value="">Не вибрано</option>{data.cvs.map((c:any)=><option value={c.id} key={c.id}>{c.filename} · {day(c.created_at)}</option>)}</select></label>{cv&&<a className="button compact" href={'/api/cv/'+cv}><Download size={14}/>Завантажити вибране CV</a>}<label>Додати адаптовану версію<input type="file" accept=".docx,.pdf,.txt" onChange={e=>{if(e.target.files?.[0])upload(e.target.files[0],selected.id);}}/></label><label>Фактична дата надсилання<input type="date" value={sent} onChange={e=>setSent(e.target.value)}/></label>{selected.email_body&&<div className="reply"><b>Чернетка листа</b><p>До: {selected.email_to}<br/>Тема: {selected.email_subject}</p><p>{selected.email_body}</p><a className="text-link" href="https://mail.google.com/mail/u/0/#drafts" target="_blank" rel="noopener noreferrer">Переглянути чернетку Gmail ↗</a></div>}<label>Особисті нотатки<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label>{data.replies.filter((r:any)=>r.application_id===selected.id).map((r:any)=><div className="reply" key={r.id}><b>{r.subject}</b><p>{r.body}</p></div>)}<p className="small-text">Перевір адресата, текст і вибране CV. Схвалення дозволяє Codex надіслати саме підготовлену чернетку Gmail. Відповіді імпортуються з її листування. Для ATS можна зафіксувати надсилання вручну.</p><button disabled={busy} className="button primary full" onClick={()=>action({action:'application',id:selected.id,status,cvId:cv,notes,sentAt:sent?sent+'T12:00:00Z':null})}>Зберегти зміни</button><button className="button full" disabled={busy||!selected.gmail_draft_id||cv!==selected.prepared_cv_id} onClick={()=>action({action:'send',id:selected.id,cvId:cv})}><Send size={16}/>Схвалити переглянуту чернетку</button></section></div>}
 </div>;
}
function Empty({title,text}:{title:string;text:string}){return <div className="empty"><div className="empty-icon"><BriefcaseBusiness size={29}/></div><h3>{title}</h3><p>{text}</p></div>;}
