import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '@/app/chatgpt-auth';
export const statuses:Record<string,string>={draft:'Чернетка',sending:'Перевірка надсилання',review:'На перегляді',approved:'Схвалено',sent:'Надіслано',reply:'Є відповідь',interview:'Співбесіда',offer:'Пропозиція',rejected:'Відмова',withdrawn:'Відкликано'};
export const defaults={categories:['backend','fullstack','automation','ai'],keywords:'Python, Flask, FastAPI, SQL, PostgreSQL, SQLAlchemy',locations:'',language:'english',excludeSenior:true,hour:9};
export function database(){if(!env.DB)throw Error('База тимчасово недоступна');return env.DB;}
export function bucket(){if(!env.BUCKET)throw Error('Сховище документів недоступне');return env.BUCKET;}
export async function owner(){const u=await getChatGPTUser();return !!u&&((import.meta.env.DEV&&u.userId==='local_seedy')||!!env.OWNER_EMAIL&&u.email.toLowerCase()===env.OWNER_EMAIL.toLowerCase());}
export function agent(req:Request){return !!env.UPDATE_TOKEN&&req.headers.get('Authorization')==='Bearer '+env.UPDATE_TOKEN;}
export function safeUrl(v:unknown){try{const u=new URL(String(v));return ['http:','https:'].includes(u.protocol)?u.href:'';}catch{return '';}}
export function txt(v:unknown,max=20000){return String(v??'').slice(0,max);}
export function date(){return new Date().toISOString();}
export function response(body:unknown,status=200){return Response.json(body,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});}
export async function getSettings(){const r=await database().prepare('SELECT value FROM settings WHERE key=?').bind('preferences').first<{value:string}>();return r?{...defaults,...JSON.parse(r.value)}:defaults;}
export async function publicState(){const a=await database().prepare('SELECT id,title,company,url,status,sent_at,reply_at,updated_at FROM applications WHERE sent_at IS NOT NULL ORDER BY sent_at DESC').all();return {applications:a.results,statuses,updatedAt:date()};}
export async function privateState(){const db=database();const r=await Promise.all([db.prepare("SELECT * FROM jobs WHERE active=1 ORDER BY score DESC,published DESC").all(),db.prepare('SELECT * FROM applications ORDER BY updated_at DESC').all(),db.prepare('SELECT id,application_id,filename,created_at,kind FROM cvs ORDER BY created_at DESC').all(),db.prepare('SELECT * FROM sessions ORDER BY started_at DESC LIMIT 1500').all(),db.prepare('SELECT * FROM runs ORDER BY at DESC LIMIT 12').all(),db.prepare('SELECT * FROM replies ORDER BY received_at DESC LIMIT 200').all(),getSettings()]);const integration=await db.prepare("SELECT value FROM settings WHERE key='automation'").first<{value:string}>();return {automation:integration?JSON.parse(integration.value):null,jobs:r[0].results,applications:r[1].results,cvs:r[2].results,sessions:r[3].results,runs:r[4].results,replies:r[5].results,preferences:r[6],statuses};}
export async function mutate(p:Record<string,any>):Promise<Record<string,any>>{const db=database(),at=date();
 if(p.action==='settings'){const v=p.value||{};const categories=(v.categories||[]).filter((x:string)=>['backend','fullstack','automation','ai','data','qa'].includes(x));const hour=Number(v.hour);if(!Number.isInteger(hour)||hour<0||hour>23)throw Error('Некоректна година');await db.prepare('INSERT OR REPLACE INTO settings(key,value) VALUES(?,?)').bind('preferences',JSON.stringify({...defaults,categories,keywords:txt(v.keywords,500),locations:txt(v.locations,500),language:['english','all'].includes(v.language)?v.language:'english',excludeSenior:!!v.excludeSenior,hour})).run();return {ok:true};}
 if(p.action==='save'){const j=await db.prepare('SELECT * FROM jobs WHERE id=? AND active=1').bind(txt(p.jobId)).first<any>();if(!j)throw Error('Вакансію не знайдено');await db.prepare('INSERT OR IGNORE INTO applications(id,job_id,title,company,url,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),j.id,j.title,j.company,j.url,'draft',at,at).run();return {ok:true};}
 if(p.action==='application'){const status=txt(p.status,30);if(!statuses[status])throw Error('Невідомий статус');const a=await db.prepare('SELECT * FROM applications WHERE id=?').bind(txt(p.id)).first<any>();if(!a)throw Error('Заявку не знайдено');const cvId=p.cvId||a.cv_id||null;if(cvId&&!await db.prepare('SELECT id FROM cvs WHERE id=?').bind(cvId).first())throw Error('CV не знайдено');const sent=p.sentAt?new Date(p.sentAt).toISOString():a.sent_at;if(a.send_lock&&status!=='sending')throw Error('Надсилання заблоковане до перевірки Gmail; автоматично повторювати його не можна');if(status==='approved'&&(!a.gmail_draft_id||a.prepared_cv_id!==cvId||!a.email_to||!a.email_body))throw Error('Спочатку потрібна підготовлена чернетка Gmail із вибраним CV');if(status==='sent'&&(!sent||!cvId))throw Error('Вкажи фактичну дату надсилання та версію CV');await db.prepare('UPDATE applications SET status=?,cv_id=?,notes=?,sent_at=?,reply_at=?,updated_at=? WHERE id=?').bind(status,cvId,txt(p.notes??a.notes),sent,['reply','interview','offer','rejected'].includes(status)?at:a.reply_at,at,a.id).run();return {ok:true};}
 if(p.action==='send'){return mutate({...p,action:'application',status:'approved'}).then(()=>({ok:true,message:'Схвалено. Codex надішле переглянуту чернетку Gmail під час наступного запуску.'}));}
 throw Error('Невідома дія');}
